using Grasshopper.Kernel;
using ParkDesign.SpacePlanner.Terrain;
using Rhino.Geometry;

namespace ParkDesign.SpacePlanner.Components;

public sealed class CutFillEstimatorComponent : GH_Component
{
    public CutFillEstimatorComponent()
        : base("Estimate Park Cut Fill", "CutFill", "Compares existing and proposed terrain meshes on a shared XY grid and reports approximate cut/fill metrics for optimization.", "Park Design", "Terrain") { }

    public override Guid ComponentGuid => new("5CC20D05-D9D2-4074-813C-9DAAB8FAB94B");
    protected override System.Drawing.Bitmap? Icon => null;

    protected override void RegisterInputParams(GH_InputParamManager parameters)
    {
        parameters.AddMeshParameter("Existing Terrain", "E", "Existing authoritative terrain mesh.", GH_ParamAccess.item);
        parameters.AddMeshParameter("Proposed Terrain", "P", "Proposed/grading terrain mesh generated by the optimization definition.", GH_ParamAccess.item);
        parameters.AddNumberParameter("Grid Spacing", "G", "Cut/fill sampling spacing in metres; smaller values improve resolution and increase computation.", GH_ParamAccess.item, 2);
        parameters.AddBooleanParameter("Run", "R", "Estimate cut and fill.", GH_ParamAccess.item, false);
    }

    protected override void RegisterOutputParams(GH_OutputParamManager parameters)
    {
        parameters.AddPointParameter("Sample Points", "P", "Proposed-terrain sample points used for volume approximation.", GH_ParamAccess.list);
        parameters.AddNumberParameter("Delta Z", "DZ", "Proposed minus existing elevation. Positive is fill; negative is cut.", GH_ParamAccess.list);
        parameters.AddNumberParameter("Cut Volume", "C", "Approximate cut volume in cubic metres.", GH_ParamAccess.item);
        parameters.AddNumberParameter("Fill Volume", "F", "Approximate fill volume in cubic metres.", GH_ParamAccess.item);
        parameters.AddNumberParameter("Net Volume", "N", "Fill minus cut in cubic metres.", GH_ParamAccess.item);
        parameters.AddNumberParameter("Total Earthwork", "TE", "Cut plus fill in cubic metres.", GH_ParamAccess.item);
        parameters.AddNumberParameter("Disturbed Area", "DA", "Approximate area where absolute elevation change exceeds 1 mm.", GH_ParamAccess.item);
        parameters.AddNumberParameter("Maximum Cut Depth", "MC", "Largest sampled cut depth in metres.", GH_ParamAccess.item);
        parameters.AddNumberParameter("Maximum Fill Depth", "MF", "Largest sampled fill depth in metres.", GH_ParamAccess.item);
        parameters.AddNumberParameter("Balance Ratio", "BR", "Absolute net volume divided by total earthwork; minimize toward zero.", GH_ParamAccess.item);
        parameters.AddTextParameter("Summary", "I", "Cut/fill approximation and resolution summary.", GH_ParamAccess.item);
    }

    protected override void SolveInstance(IGH_DataAccess data)
    {
        Mesh? existing = null;
        Mesh? proposed = null;
        var spacing = 2d;
        var run = false;
        if (!data.GetData(0, ref existing) || existing is null) return;
        if (!data.GetData(1, ref proposed) || proposed is null) return;
        data.GetData(2, ref spacing);
        data.GetData(3, ref run);
        if (!run) return;
        if (spacing <= 0)
        {
            AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Grid Spacing must be greater than zero metres.");
            return;
        }

        var existingBox = existing.GetBoundingBox(true);
        var proposedBox = proposed.GetBoundingBox(true);
        var minX = Math.Max(existingBox.Min.X, proposedBox.Min.X);
        var maxX = Math.Min(existingBox.Max.X, proposedBox.Max.X);
        var minY = Math.Max(existingBox.Min.Y, proposedBox.Min.Y);
        var maxY = Math.Min(existingBox.Max.Y, proposedBox.Max.Y);
        if (maxX <= minX || maxY <= minY)
        {
            AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Existing and proposed terrain meshes have no shared XY extent.");
            return;
        }
        var xCount = Math.Max(1, (int)Math.Ceiling((maxX - minX) / spacing));
        var yCount = Math.Max(1, (int)Math.Ceiling((maxY - minY) / spacing));
        if ((long)xCount * yCount > 250000)
        {
            AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Cut/fill comparison exceeds 250,000 samples. Increase Grid Spacing.");
            return;
        }

        var points = new List<Point3d>();
        var deltas = new List<double>();
        for (var ix = 0; ix < xCount; ix++)
        for (var iy = 0; iy < yCount; iy++)
        {
            var x = minX + Math.Min(maxX - minX, (ix + 0.5) * spacing);
            var y = minY + Math.Min(maxY - minY, (iy + 0.5) * spacing);
            if (!TerrainMeshSampler.TrySample(existing, x, y, out var existingSample)) continue;
            if (!TerrainMeshSampler.TrySample(proposed, x, y, out var proposedSample)) continue;
            points.Add(proposedSample.Point);
            deltas.Add(proposedSample.Point.Z - existingSample.Point.Z);
        }
        if (deltas.Count == 0)
        {
            AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "No vertically corresponding terrain samples were found.");
            return;
        }

        var cellArea = spacing * spacing;
        var cut = deltas.Where(delta => delta < 0).Sum(delta => -delta * cellArea);
        var fill = deltas.Where(delta => delta > 0).Sum(delta => delta * cellArea);
        var total = cut + fill;
        var disturbed = deltas.Count(delta => Math.Abs(delta) > 0.001) * cellArea;
        var maximumCut = deltas.Where(delta => delta < 0).Select(delta => -delta).DefaultIfEmpty(0).Max();
        var maximumFill = deltas.Where(delta => delta > 0).DefaultIfEmpty(0).Max();
        var balance = total <= 1e-9 ? 0 : Math.Abs(fill - cut) / total;
        data.SetDataList(0, points);
        data.SetDataList(1, deltas);
        data.SetData(2, cut);
        data.SetData(3, fill);
        data.SetData(4, fill - cut);
        data.SetData(5, total);
        data.SetData(6, disturbed);
        data.SetData(7, maximumCut);
        data.SetData(8, maximumFill);
        data.SetData(9, balance);
        data.SetData(10, $"Approximate sampled earthwork at {spacing:0.##} m: cut {cut:0.##} m3, fill {fill:0.##} m3, net {fill - cut:0.##} m3, disturbed {disturbed:0.##} m2, balance {balance:0.###}. Use a finer grid for final comparison; this is not a survey quantity.");
    }
}
