using Grasshopper.Kernel;
using Rhino.Geometry;

namespace ParkDesign.SpacePlanner.Components;

public sealed class SelectBarahaCandidatesComponent : GH_Component
{
    public SelectBarahaCandidatesComponent()
        : base(
            "Select Baraha Candidates",
            "SelectBaraha",
            "Selects a ranked, boundary-safe, non-overlapping set from the alternative Baraha footprints generated by ParkBubbles.",
            "Park Design",
            "Terrain")
    {
    }

    public override Guid ComponentGuid => new("A50A3DA5-1E1B-4438-A399-0F8BF1E8FCEC");
    protected override System.Drawing.Bitmap? Icon => null;

    protected override void RegisterInputParams(GH_InputParamManager parameters)
    {
        parameters.AddCurveParameter("Boundary", "B", "Connect ParkBubbles Resolved Boundary.", GH_ParamAccess.item);
        parameters.AddCurveParameter("Candidate Footprints", "C", "Connect ParkBubbles Baraha Candidate Footprints. Their existing score order is preserved.", GH_ParamAccess.list);
        parameters.AddTextParameter("Candidate Data", "D", "Connect ParkBubbles Baraha Candidate Data.", GH_ParamAccess.list);
        parameters.AddIntegerParameter("Maximum Count", "N", "Maximum alternatives to select. This is a visible designer decision, not a requirement inferred from the brief.", GH_ParamAccess.item, 3);
        parameters.AddNumberParameter("Clearance", "G", "Additional edge-to-edge clearance between selected Barahas in metres.", GH_ParamAccess.item, 2);
        parameters.AddBooleanParameter("Run", "R", "Select candidates.", GH_ParamAccess.item, false);
        parameters[2].Optional = true;
    }

    protected override void RegisterOutputParams(GH_OutputParamManager parameters)
    {
        parameters.AddCurveParameter("Selected Footprints", "S", "Boundary-safe, mutually separated Baraha footprints.", GH_ParamAccess.list);
        parameters.AddPointParameter("Selected Centers", "P", "Centers matching Selected Footprints.", GH_ParamAccess.list);
        parameters.AddTextParameter("Selected Data", "D", "Candidate data matching Selected Footprints.", GH_ParamAccess.list);
        parameters.AddCurveParameter("Rejected Footprints", "X", "Alternatives rejected by boundary, overlap, validity, or count.", GH_ParamAccess.list);
        parameters.AddTextParameter("Decisions", "I", "Selection/rejection audit records.", GH_ParamAccess.list);
        parameters.AddTextParameter("Summary", "M", "Selection summary.", GH_ParamAccess.item);
    }

    protected override void SolveInstance(IGH_DataAccess data)
    {
        Curve? boundary = null;
        var candidates = new List<Curve>();
        var candidateData = new List<string>();
        var maximumCount = 3;
        var clearance = 2d;
        var run = false;
        if (!data.GetData(0, ref boundary) || boundary is null) return;
        data.GetDataList(1, candidates);
        data.GetDataList(2, candidateData);
        data.GetData(3, ref maximumCount);
        data.GetData(4, ref clearance);
        data.GetData(5, ref run);
        if (!run) return;

        if (!boundary.IsClosed || !boundary.IsPlanar())
        {
            AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Boundary must be closed and planar.");
            return;
        }
        if (maximumCount < 0 || clearance < 0)
        {
            AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Maximum Count and Clearance cannot be negative.");
            return;
        }

        var tolerance = Rhino.RhinoDoc.ActiveDoc?.ModelAbsoluteTolerance ?? .01;
        var selected = new List<(Curve Curve, Point3d Center, double Radius, int Index)>();
        var rejected = new List<Curve>();
        var decisions = new List<string>();
        for (var index = 0; index < candidates.Count; index++)
        {
            var candidate = candidates[index];
            var properties = candidate.IsClosed ? AreaMassProperties.Compute(candidate) : null;
            if (properties is null || properties.Area <= tolerance * tolerance)
            {
                rejected.Add(candidate);
                decisions.Add($"candidate {index + 1}: rejected_invalid_closed_footprint");
                continue;
            }

            var center = properties.Centroid;
            var radius = Math.Sqrt(properties.Area / Math.PI);
            var safelyInside = Enumerable.Range(0, 32).All(sample =>
            {
                var parameter = candidate.Domain.ParameterAt(sample / 32d);
                return boundary.Contains(candidate.PointAt(parameter), Plane.WorldXY, tolerance) != PointContainment.Outside;
            });
            if (!safelyInside)
            {
                rejected.Add(candidate);
                decisions.Add($"candidate {index + 1}: rejected_outside_boundary");
                continue;
            }

            if (selected.Any(item => center.DistanceTo(item.Center) < radius + item.Radius + clearance))
            {
                rejected.Add(candidate);
                decisions.Add($"candidate {index + 1}: rejected_overlap_or_clearance");
                continue;
            }
            if (selected.Count >= maximumCount)
            {
                rejected.Add(candidate);
                decisions.Add($"candidate {index + 1}: rejected_maximum_count");
                continue;
            }

            selected.Add((candidate, center, radius, index));
            decisions.Add($"candidate {index + 1}: selected radius={radius:0.##}m rank={index + 1}");
        }

        data.SetDataList(0, selected.Select(item => item.Curve));
        data.SetDataList(1, selected.Select(item => item.Center));
        data.SetDataList(2, selected.Select(item => item.Index < candidateData.Count ? candidateData[item.Index] : $"candidate_rank={item.Index + 1}"));
        data.SetDataList(3, rejected);
        data.SetDataList(4, decisions);
        data.SetData(5, $"Selected {selected.Count}/{candidates.Count} Baraha alternatives with {clearance:0.##} m clearance; maximum count {maximumCount}. Designer review remains required.");
    }
}
